name: Build and Publish storybook to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the action only when files change in the folders defined here
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install all NPM dependencies and build storybook as a static files
      - name: Install Packages
        run: |
          npm
          npm run build-storybook

      # Deploy storybook static files to the github pages
      - name: Deploy Storybook to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: docs
